const labels = {
  critical: "严重",
  high: "高",
  medium: "中",
  low: "低",
  unknown: "待确认",
  complete: "数据完整",
  missing_sales: "缺销量",
  missing_config: "缺补货配置",
  missing_inventory: "缺库存",
  invalid_sales: "销量异常",
  invalid_config: "配置异常",
  replenish_now: "立即补货",
  prepare_replenishment: "准备补货",
  clearance_or_reduce_replenishment: "清仓/控补",
  complete_missing_data: "补全数据",
  keep_monitoring: "持续观察",
  P0: "P0",
  P1: "P1",
  P2: "P2",
  P3: "P3",
  pending: "待处理",
  resolved: "已解决",
  ignored: "已忽略",
  rising: "上升",
  stable: "稳定",
  declining: "下滑",
  no_sales: "无销量",
  none: "无需审批",
  operator: "运营审批",
  manager: "主管审批",
  owner: "负责人审批",
  stockout: "断货风险",
  replenishment: "补货建议",
  overstock: "高库存",
  inventory_exception: "库存异常",
  data_quality: "数据问题",
  stockout_warning: "断货预警",
  replenishment_suggestion: "补货建议",
  overstock_warning: "滞销/高库存",
  unfulfillable_inventory_alert: "不可售异常",
  data_missing_alert: "数据缺失",
};

function RiskBadge({ value }) {
  const normalized = value || "unknown";
  return <span className={`risk-badge ${normalized}`}>{labels[normalized] || normalized}</span>;
}

export default RiskBadge;
